"""Read-only provenance census for the farm-launch recurrence source."""
from __future__ import annotations
import argparse, json, sqlite3
from pathlib import Path

def rows(c, sql, args=()): return [dict(r) for r in c.execute(sql,args)]

def main():
 p=argparse.ArgumentParser(); p.add_argument('--db',default='database/wt_ops_v2.db'); p.add_argument('--output',default='docs/audits/wt_farm_launches_evidence_provenance.v1.json'); a=p.parse_args()
 c=sqlite3.connect(f'file:{a.db}?mode=ro',uri=True); c.row_factory=sqlite3.Row
 unknown='''SELECT fl.* FROM wt_farm_launches fl LEFT JOIN wt_confirmed_treasuries t ON t.treasury=fl.funder LEFT JOIN wt_discovered_subprovs sp ON sp.subprov=fl.funder WHERE t.treasury IS NULL AND sp.subprov IS NULL'''
 persistent=f'''WITH u AS ({unknown}), p AS (SELECT funder FROM u GROUP BY funder HAVING COUNT(*)>=3) SELECT * FROM u WHERE funder IN (SELECT funder FROM p)'''
 role_overlap=c.execute('''SELECT COUNT(DISTINCT f.mint) FROM wt_farm_launches f JOIN wt_walkback_transaction_roles r ON r.mint=f.mint''').fetchone()[0]
 selected_overlap=c.execute("""SELECT COUNT(DISTINCT f.mint) FROM wt_farm_launches f JOIN wt_walkback_edge_candidates e ON e.mint=f.mint AND e.candidate_parent=f.funder AND e.selection_status='SELECTED'""").fetchone()[0]
 linked_role=c.execute("""SELECT COUNT(DISTINCT f.mint) FROM wt_farm_launches f JOIN wt_walkback_edge_candidates e ON e.mint=f.mint AND e.candidate_parent=f.funder AND e.selection_status='SELECTED' JOIN wt_walkback_transaction_roles r ON r.mint=e.mint AND r.signature=e.signature""").fetchone()[0]
 reps=rows(c,f'''WITH p AS ({persistent}) SELECT mint,creator,funder,seed_sol,migrated_at,detected_at FROM p ORDER BY CASE WHEN seed_sol<=0 THEN 0 ELSE 1 END,seed_sol,migrated_at,mint LIMIT 50''')
 census=rows(c,f'''WITH p AS ({persistent}), e AS (SELECT mint,candidate_parent,MIN(amount_lamports) amount FROM wt_walkback_edge_candidates WHERE selection_status='SELECTED' GROUP BY mint,candidate_parent) SELECT p.funder,COUNT(*) FARM_LAUNCH_COUNT,COUNT(DISTINCT p.creator) DISTINCT_CREATORS,COUNT(DISTINCT p.mint) DISTINCT_MINTS,MIN(e.amount) MIN_AMOUNT,MAX(e.amount) MAX_AMOUNT,SUM(e.amount IS NOT NULL) ROLE_EVIDENCE_COVERAGE,SUM(CASE WHEN e.amount IS NOT NULL THEN 0 ELSE 1 END) INSUFFICIENT_ROW_COUNT FROM p LEFT JOIN e ON e.mint=p.mint AND e.candidate_parent=p.funder GROUP BY p.funder ORDER BY FARM_LAUNCH_COUNT DESC,p.funder''')
 d={
  'schema_version':'wt_farm_launches_evidence_provenance.v1','mode':'READ_ONLY','FILTER_ACTIVATED':False,'UNKNOWN_RANKING_MUTATION':0,
  'schema':{'COLUMN_NAMES':[r['name'] for r in rows(c,'PRAGMA table_info(wt_farm_launches)')],'PRIMARY_KEY':['mint'],'UNIQUE_CONSTRAINTS':['mint primary key'],'INDEXES':rows(c,'PRAGMA index_list(wt_farm_launches)'),'FOREIGN_KEYS':rows(c,'PRAGMA foreign_key_list(wt_farm_launches)'),'ROW_COUNT':c.execute('SELECT COUNT(*) FROM wt_farm_launches').fetchone()[0],'MIN_CREATE_TIME':'NOT_RETAINED','MAX_CREATE_TIME':'NOT_RETAINED','MIN_MIGRATED_AT':c.execute('SELECT MIN(migrated_at) FROM wt_farm_launches').fetchone()[0],'MAX_MIGRATED_AT':c.execute('SELECT MAX(migrated_at) FROM wt_farm_launches').fetchone()[0]},
  'writers':[{'path':'src/core/farm_detector.py','function':'run_farm_scan','sql':'INSERT OR REPLACE INTO wt_farm_launches (mint,funder,creator,peak_mc,migrated_at,wrap_close,seed_sol) VALUES (?,?,?,?,?,?,?)','caller':'src/core/operation_scheduler.py intake cadence; module __main__','trigger':'recent migrated single-use creator token','input':'token_analysis row + _trace_funder_evidence creator oldest transaction','transaction':'short post-RPC ops-db transaction','database':'OPS_DB / database/wt_ops_v2.db'}],
  'live_flow':['token_analysis: mint, earliest_tx_creator, peak, migrated_at','run_farm_scan filters recent single-use creators','_trace_funder_evidence: getSignaturesForAddress creator -> oldest signature -> getTransaction jsonParsed','in-memory raw tx, signature, blockTime, account keys, balances, parsed types','legacy funder projection: lowest non-creator balance delta; wrap_close; seed_sol','wt_farm_launches compact insert'],
  'pre_insert_fields':{'MINT_AVAILABLE':True,'CREATOR_AVAILABLE':True,'FUNDER_AVAILABLE':True,'DEFINING_SIGNATURE_AVAILABLE':False,'FUNDING_SIGNATURE_AVAILABLE':True,'TRANSFER_SOURCE_AVAILABLE':'RAW_TX_AVAILABLE_BUT_NOT_SEMANTICALLY_DECODED_BY_LEGACY_FARM_PROJECTION','TRANSFER_DESTINATION_AVAILABLE':'RAW_TX_AVAILABLE_BUT_NOT_SEMANTICALLY_DECODED_BY_LEGACY_FARM_PROJECTION','TRANSFER_AMOUNT_AVAILABLE':'BALANCE_DELTA_ONLY','TRANSFER_TIME_AVAILABLE':True,'LAUNCH_TIME_AVAILABLE':'MIGRATION_TIME_ONLY','SIGNERS_AVAILABLE':'RAW_TX_ONLY','FEE_PAYER_AVAILABLE':'RAW_TX_ONLY','OUTER_INSTRUCTIONS_AVAILABLE':'RAW_TX_ONLY','INNER_INSTRUCTIONS_AVAILABLE':'RAW_TX_ONLY','INTERMEDIARY_ROUTE_AVAILABLE':'RAW_TX_ONLY','LAUNCH_COUPLING_AVAILABLE':'creator oldest tx relation','RAW_TRANSACTION_AVAILABLE':True},
  'evidence_loss':{'result':'FARM_LAUNCH_EVIDENCE_PARTIALLY_OBSERVED','FIRST_STAGE_WITH_RICH_EVIDENCE':'_trace_funder_evidence after getTransaction','LAST_STAGE_WITH_RICH_EVIDENCE':'in-memory FunderTrace before short persistence transaction','EXACT_STAGE_WHERE_FIELDS_ARE_DROPPED':'legacy tuple/projection into launch_rows','FIELDS_DROPPED':['funding_signature','raw transaction','blockTime','signers','fee payer','parsed transfer source/destination','instruction shapes','route semantics'],'WHY':'original compact farm aggregation stored only cluster fields'},
  'role_table':{'ROW_COUNT':c.execute('SELECT COUNT(*) FROM wt_walkback_transaction_roles').fetchone()[0],'DISTINCT_SIGNATURE_COUNT':c.execute('SELECT COUNT(DISTINCT signature) FROM wt_walkback_transaction_roles').fetchone()[0],'DISTINCT_MINT_COUNT':c.execute('SELECT COUNT(DISTINCT mint) FROM wt_walkback_transaction_roles').fetchone()[0],'MIN_RETAINED_AT':c.execute('SELECT MIN(first_observed_at) FROM wt_walkback_transaction_roles').fetchone()[0],'MAX_RETAINED_AT':c.execute('SELECT MAX(last_observed_at) FROM wt_walkback_transaction_roles').fetchone()[0],'FARM_ROW_OVERLAP_COUNT':role_overlap,'FARM_ROW_OVERLAP_PERCENT':round(role_overlap*100/c.execute('SELECT COUNT(*) FROM wt_farm_launches').fetchone()[0],2)},
  'join_key':{'BEST_JOIN_KEY':'mint + funding_signature via new wt_farm_launch_evidence linkage','CURRENT_JOIN_KEY_COVERAGE':0,'HISTORICAL_SELECTED_EDGE_FALLBACK':selected_overlap,'HISTORICAL_EXACT_ROLE_JOIN':linked_role,'JOIN_KEY_AMBIGUITY':'farm rows presently retain no signature'},
  'current_unknown_baseline':{'PERSISTENT_REPEAT_FUNDERS':c.execute(f'WITH p AS ({persistent}) SELECT COUNT(DISTINCT funder) FROM p').fetchone()[0],'FARM_LAUNCH_ROWS':c.execute(f'WITH p AS ({persistent}) SELECT COUNT(*) FROM p').fetchone()[0]},
  'representative_rows':reps,'current_58_funder_census':census,
  'recommendation':{'RECOMMENDED_RETENTION_MODEL':'OPTION_D: canonical generic role row plus additive farm-to-role linkage','RECOMMENDED_WRITER_OWNER':'farm_detector after its existing getTransaction','RECOMMENDED_READER_OWNER':'future farm edge-quality projection','TARGET_TABLE_OR_PROJECTION':'wt_farm_launch_evidence -> wt_walkback_transaction_roles','ZERO_EXTRA_RPC_FEASIBLE':True,'conditions':'only for prospective farm rows whose existing scanner transaction is decoded and linked; unresolved transactions remain INSUFFICIENT_TO_CLASSIFY','HISTORICAL_LOCAL_BACKFILL_COUNT':0,'HISTORICAL_INSUFFICIENT_COUNT':c.execute(f'WITH p AS ({persistent}) SELECT COUNT(*) FROM p').fetchone()[0],'HISTORICAL_RPC_BACKFILL_REQUIRED_COUNT':'NOT_AUTHORIZED_NOT_PERFORMED'}
 }
 Path(a.output).write_text(json.dumps(d,sort_keys=True,indent=2)+'\n'); print(json.dumps(d['current_unknown_baseline']))
if __name__=='__main__': main()
