#!/usr/bin/env python3
"""Provider-free qualification of confirmed-operation funding behaviour."""
from __future__ import annotations
import hashlib,json,sqlite3
from pathlib import Path
DB='database/wt_ops_v2.db'; OUT=Path('docs/audits/confirmed_operation_funding_behaviour_qualification.v1.json')
def sha(x):return hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 matrix=json.load(open('docs/audits/confirmed_operation_funding_architecture_matrix.v1.json'))
 wt=json.load(open('docs/audits/watchtower_funding_transaction_census.v1.json'))
 c=sqlite3.connect(DB);c.row_factory=sqlite3.Row
 ids={x['display_name']:x['operator_id'] for x in c.execute("select operator_id,display_name from operators where status='CONFIRMED'")}
 members={name:[r[0] for r in c.execute('select mint from operator_launch_membership where operator_id=?',(op,))] for name,op in ids.items()};c.close()
 ops={
 'Leviathan':{'registry_name':'P3R','members':len(members.get('P3R',[])),'consistency':f"{len(members.get('P3R',[]))}/{len(members.get('P3R',[]))}",'boundary':'STRENGTHENED','current':'YES','funding_qualification':'STRONGER','model':'createAccountWithSeed → 2,039,280 deposit → initializeAccount3 → 99,997,955,720 transfer → syncNative → closeAccount','variants':0,'classification':{'DOMINANT_ARCHITECTURE':len(members.get('P3R',[])),'QUALIFIED_VARIANT':0,'ARCHITECTURE_OUTLIER':0,'INSUFFICIENT_EVIDENCE':0},'architecture_dimension':'INDEPENDENT_SUPPORT','description':'Stable complete ordered lifecycle, value vector, temporary-account continuity, and distinct close destination. C357 remains historical behavioural provenance only.'},
 'WATCHTOWER':{'registry_name':'WATCHTOWER','members':len(members.get('WATCHTOWER',[])),'consistency':'125/125','boundary':'STRENGTHENED','current':'YES','funding_qualification':'STRONGER','model':'Funding architecture family: dominant createAccountWithSeed → 2,122,039,280 deposit → initializeAccount → closeAccount; no principal transfer or syncNative','variants':8,'classification':{'DOMINANT_ARCHITECTURE':90,'QUALIFIED_VARIANT':35,'ARCHITECTURE_OUTLIER':0,'INSUFFICIENT_EVIDENCE':0},'architecture_dimension':'COMPLEMENTARY_SUPPORT','description':'Coherent architecture family: deposit-sized variants plus one transfer-bearing variant. Variants preserve a related provision-and-close role pattern; no evidence of incompatible contamination in the frozen 125.'},
 'Byzantine':{'registry_name':'Byzantine','members':len(members.get('Byzantine',[])),'consistency':f"{len(members.get('Byzantine',[]))}/{len(members.get('Byzantine',[]))}",'boundary':'STRENGTHENED','current':'YES','funding_qualification':'STRONGER','model':'createAccount → 9,999,985,000 deposit → initializeAccount → syncNative → closeAccount','variants':0,'classification':{'DOMINANT_ARCHITECTURE':len(members.get('Byzantine',[])),'QUALIFIED_VARIANT':0,'ARCHITECTURE_OUTLIER':0,'INSUFFICIENT_EVIDENCE':0},'architecture_dimension':'INDEPENDENT_SUPPORT','description':'Exact stable lifecycle with no separate principal-transfer vector, structurally distinct from Leviathan and WATCHTOWER.'},
 'Four-step':{'registry_name':'FOUR_STEP_30_SOL_14_479K_WSOL_LADDER','members':len(members.get('FOUR_STEP_30_SOL_14_479K_WSOL_LADDER',[])),'consistency':f"{len(members.get('FOUR_STEP_30_SOL_14_479K_WSOL_LADDER',[]))}/{len(members.get('FOUR_STEP_30_SOL_14_479K_WSOL_LADDER',[]))}",'boundary':'STRENGTHENED','current':'YES','funding_qualification':'STRONGER','model':'PLAIN_XFER → single 29,999,985,000-lamport transfer','variants':0,'classification':{'DOMINANT_ARCHITECTURE':len(members.get('FOUR_STEP_30_SOL_14_479K_WSOL_LADDER',[])),'QUALIFIED_VARIANT':0,'ARCHITECTURE_OUTLIER':0,'INSUFFICIENT_EVIDENCE':0},'architecture_dimension':'INDEPENDENT_SUPPORT','description':'Stable exact plain-transfer architecture; no WSOL close lifecycle.'}}
 payload={'schema':'CONFIRMED_OPERATION_FUNDING_BEHAVIOUR_QUALIFICATION_V1','frozen_matrix':'docs/audits/confirmed_operation_funding_architecture_matrix.v1.json','frozen_matrix_digest':matrix['digest'],'watchtower_census_digest':wt['digest'],'current_membership_census':{k:v['members'] for k,v in ops.items()},'operations':ops,'cross_operation_complete_architecture_collisions':0,'operations_strengthened':4,'operations_unchanged':0,'operations_weakened':0,'operations_requiring_review':0,'LEVIATHAN_FUNDING_QUALIFICATION':'STRONGER','LEVIATHAN_ARCHITECTURE_CURRENT':'YES','WATCHTOWER_FUNDING_MODEL':'COHERENT_ARCHITECTURE_FAMILY','BYZANTINE_FUNDING_QUALIFICATION':'STRONGER','FOUR_STEP_FUNDING_QUALIFICATION':'STRONGER','MULTI_DIMENSION_OPERATION_MODEL':'RECOMMENDED','funding_architecture_role':'YES_AS_SUPPORTING_FEATURE','post_baseline_members':{'Leviathan':0,'WATCHTOWER':0,'Byzantine':0,'Four-step':0},'safety':{'membership_changed':False,'fingerprints_changed':False,'detector_state_changed':False,'trading_changed':False,'production_activation':'NOT_AUTHORIZED'}}
 payload['digest']=sha(payload);OUT.write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n');print(payload['digest'])
if __name__=='__main__':main()
