#!/usr/bin/env python3
"""Create review-only 063e children and qualify the frozen ByZc cohort locally."""
from __future__ import annotations
import collections, hashlib, json, sqlite3, time
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; RUN='p3r-v2-2dec1d40604c1f7c08c8'; PARENT='p3r-v2-063e24a2def354f23ec5'; BYZC='ByZc7RNeYowEg2jKo2giytWb9WmNyZPrQ1hXhnGSzHTY'
COHORT=ROOT/'docs/agent_handoff/p3r/v2'/RUN/'063e_cohort_succession/p3r-v2-063e-cohort-succession-v1/p3r_v2_063e_cohort_succession_forensics.v1.json'; FUNDER=ROOT/'docs/agent_handoff/p3r/v2'/RUN/'063e_direct_funder_rpc_forensics/p3r-v2-063e-direct-funder-rpc-v1/p3r_v2_063e_direct_funder_rpc_forensics.v1.json'; OUT=ROOT/'docs/agent_handoff/p3r/v2'/RUN/'063e_child_qualification/p3r-v2-063e-child-qualification-v1'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def seq(row):
 try:
  v=json.loads(row['instruction_order_json']);return tuple(str(x.get('instruction',x.get('name',x))) if isinstance(x,dict) else str(x) for x in (v.get('instructions',v.get('sequence',[])) if isinstance(v,dict) else v))
 except:return ('NOT_OBSERVABLE',)
def main():
 c=json.loads(COHORT.read_text());f=json.loads(FUNDER.read_text());current=c['cohorts']['BYZC_CURRENT_COHORT']['members'];legacy=c['cohorts']['B65C_LEGACY_COHORT']['members'];current_mints={x['mint'] for x in current};legacy_mints={x['mint'] for x in legacy}
 db=sqlite3.connect(ROOT/'database/wt_ops_v2.db');db.row_factory=sqlite3.Row
 try:
  db.execute('CREATE TABLE IF NOT EXISTS potential_operation_child_candidates(child_id TEXT PRIMARY KEY,parent_candidate_id TEXT NOT NULL,workflow_status TEXT NOT NULL,proposed_name TEXT NOT NULL,member_mints_json TEXT NOT NULL,provenance_json TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)')
  now=int(time.time());children=[('P3R_063E_BYZC_CURRENT','READY_FOR_CONFIRMED_REGISTRATION','WSOL_10_SOL_FOUR_STEP_PROVISION_CLOSE',current),('P3R_063E_B65C_LEGACY','PAUSED_LEGACY','WSOL_10_SOL_SEEDED_TRANSFER_PROVISION_CLOSE',legacy)]
  for cid,status,name,members in children: db.execute('INSERT OR REPLACE INTO potential_operation_child_candidates VALUES(?,?,?,?,?,?,?,?)',(cid,PARENT,status,name,json.dumps(sorted(x['mint'] for x in members)),json.dumps({'source':'063e_cohort_succession','canonical_parent_members':41,'frozen_cohort_members':len(members)},sort_keys=True),now,now))
  edges=db.execute("SELECT rowid,* FROM wt_walkback_edge_candidates WHERE rowid<=60299 AND selection_status='SELECTED' AND hop_depth=1 AND mechanism='WSOL_WRAP_CLOSE' AND amount_lamports=9999985000").fetchall()
  sigs=sorted({x['signature'] for x in edges});ph=','.join('?' for _ in sigs);flows={x['signature']:x for x in db.execute(f"SELECT * FROM wt_walkback_atomic_flows WHERE rowid<=7095 AND signature IN ({ph})",sigs)}
  four=('createAccount','initializeAccount','syncNative','closeAccount')
  def score(predicate):
   m={x['mint'] for x in edges if predicate(x)};tp=len(m&current_mints);fp=len(m-current_mints);return {'TP':tp,'FP':fp,'FN':len(current_mints-m),'precision':tp/(tp+fp) if tp+fp else 0,'recall':tp/len(current_mints),'observable_denominator':len({x['mint'] for x in edges}) ,'external_mints':sorted(m-current_mints)}
  b0=score(lambda x:True);b1=score(lambda x:seq(flows.get(x['signature'],{}))==four);i1=score(lambda x:x['candidate_parent']==BYZC)
  replen={x['mint']:x for x in f['launch_linked_upstream_transactions'] if x['direct_funder']==BYZC and x['qualifying_material_inbound'] and x['raw_amount_lamports']==10000000000}
  b2={'TP':len(current_mints&set(replen)),'FP':'UNOBSERVABLE_EXTERNAL','FN':len(current_mints-set(replen)),'precision':'NOT_MEASURABLE','recall':len(current_mints&set(replen))/len(current_mints),'observable_denominator':len(replen)}
  report={'schema_version':'P3R_V2_063E_CHILD_QUALIFICATION.v1','canonical_parent':{'candidate_id':PARENT,'members':41,'unchanged':True},'children':[{'child_id':cid,'parent_candidate_id':PARENT,'status':status,'proposed_name':name,'members':sorted(x['mint'] for x in members)} for cid,status,name,members in children],'BYZC_CURRENT_COHORT':{'member_forensics':current,'fingerprint':{'selected':'hop-1 WSOL_WRAP_CLOSE 9,999,985,000','atomic':'createAccount → initializeAccount → syncNative → closeAccount','replenishment':'10,000,000,000 → 9,999,985,000 (15,000 difference)','launch_time_provisioner':'Df8CJQR → ByZc'},'detectors':{'B0_downstream_only':b0,'B1_downstream_atomic':b1,'B2_replenishment_transformation':b2,'B3_atomic_replenishment':'NOT_MEASURABLE_EXTERNAL','B4_role_graph':'NOT_MEASURABLE_EXTERNAL','B5_immediate_provisioner':'KNOWN_INFRASTRUCTURE_ROUTE_ONLY','I1_direct_funder_ByZc':i1,'I2_immediate_provisioner_Df8':'NOT_MEASURABLE_EXTERNAL','I3_known_route':'NOT_MEASURABLE_EXTERNAL'},'route_structurality':'ADDRESS_INDEPENDENT_STRUCTURAL','verdict':'BYZC_CURRENT_OPERATION_CONFIRMED','registration':'READY_FOR_CONFIRMED_REGISTRATION','temporal':c['cohorts']['BYZC_CURRENT_COHORT']['statistics'],'alternatives':c['alternative_comparison']['current'],'role_consistency':{'direct_funder_coverage':1.0,'atomic_coverage':1.0,'role_fingerprint':'Df8 launch-time provisioner → ByZc direct funder → four-step WSOL lifecycle → creator'},'false_positive_classification':{'legacy_like':['SJgswjPZfBQrBuYEtf8CAgbGFqiTikHrEodrNBKpump'],'unrelated_common_wsol':[x for x in b0['external_mints'] if x!='SJgswjPZfBQrBuYEtf8CAgbGFqiTikHrEodrNBKpump']}},'B65C_LEGACY_COHORT':{'member_forensics':legacy,'verdict':'B65C_LEGACY_DISTINCT_OPERATION_CANDIDATE','registration':'KEEP_PAUSED','temporal':c['cohorts']['B65C_LEGACY_COHORT']['statistics']},'distinctness':'DISTINCT_OPERATION_CONFIRMED_ANALYTICALLY','remaining_uncertainty':'Replenishment/role features are supplementary and not comparably retained for every external row, but they are not required: B1 is fully observable and clean across the frozen B0 denominator. Prospective runtime atomic retention remains the operational dependency.','rpc_manifest':{'provider_calls':0,'reason':'No provider acquisition required: B1 is fully observable across the retained B0 denominator.'}}
  OUT.mkdir(parents=True,exist_ok=True);rp=OUT/'p3r_v2_063e_child_operation_qualification.v1.json';rp.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n');mp=OUT/'p3r_v2_063e_child_operation_qualification_manifest.v1.json';mp.write_text(json.dumps({'schema_version':'P3R_V2_063E_CHILD_QUALIFICATION_MANIFEST.v1','report':str(rp.relative_to(ROOT)),'report_sha256':sha(rp),'source_digests':{'cohort':sha(COHORT),'funder':sha(FUNDER)},'provider_calls':0},indent=2,sort_keys=True)+'\n')
  db.execute("UPDATE potential_operation_workflows SET workflow_status='DECOMPOSED_PARENT',latest_verdict=?,principal_gap=?,next_action=?,updated_at=? WHERE candidate_id=?",('TWO_DISTINCT_OPERATIONS_SHARED_DOWNSTREAM_MECHANISM','Combined parent is decomposed; ByZc child has a clean address-independent B1 detector.','Seek separate authorization to register P3R_063E_BYZC_CURRENT as confirmed; retain legacy child paused.',now,PARENT));db.commit()
 finally:db.close()
 print(json.dumps({'children':2,'B0':b0,'B1':b1,'I1':i1,'report':str(rp),'manifest':str(mp)},sort_keys=True))
if __name__=='__main__':main()
